const axios = require("axios");

const PRIORITY_MAP = {
  Critical: "Highest",
  High:     "High",
  Medium:   "Medium",
  Low:      "Low",
};

function buildJiraDescription(rec, finding) {
  const lines = [];
  lines.push("h2. Vulnerability details");
  lines.push(`*Scanner:* ${finding?.scanner || "Unknown"}`);
  lines.push(`*Severity:* ${finding?.severity || rec.priority || "Unknown"}`);
  if (rec.cvss_score) lines.push(`*CVSS Score:* ${rec.cvss_score} — ${rec.cvss_vector || ""}`);
  if (rec.owasp_category) lines.push(`*OWASP Category:* ${rec.owasp_category}`);
  if (rec.ai_risk_score) lines.push(`*AI Risk Score:* ${rec.ai_risk_score}/100`);
  if (rec.confidence) lines.push(`*Confidence:* ${rec.confidence}%`);
  lines.push("");
  lines.push("h2. Content");
  if (rec.content) {
    lines.push(rec.content.replace(/\*\*(.*?)\*\*/g, "*$1*"));
  }
  if (rec.code_fix_example) {
    lines.push("");
    lines.push("h2. Recommended fix");
    lines.push("{code:language=javascript}");
    lines.push(rec.code_fix_example);
    lines.push("{code}");
  }
  lines.push("");
  lines.push("----");
  lines.push(`_Generated by DevSecOps platform — recommendation #${rec.id}_`);
  return lines.join("\n");
}

async function createJiraIssue({ recommendation, finding, approvedByEmail }) {
  const baseUrl    = process.env.JIRA_BASE_URL;
  const email      = process.env.JIRA_EMAIL;
  const apiToken   = process.env.JIRA_API_TOKEN;
  const projectKey = process.env.JIRA_PROJECT_KEY;

  if (!baseUrl || !email || !apiToken || !projectKey) {
    throw new Error("Missing Jira config — check your secrets");
  }

  const auth = Buffer.from(`${email}:${apiToken}`).toString("base64");
  const title = finding?.title || `Security finding #${recommendation.finding_id}`;

  const labels = ["security"];
  if (finding?.scanner) labels.push(finding.scanner.toLowerCase().replace(/\s+/g, "-"));
  if (recommendation.owasp_category) labels.push(recommendation.owasp_category.toLowerCase().replace(/\s+/g, "-").slice(0, 20));

  const payload = {
    fields: {
      project:     { key: projectKey },
      summary:     `[SEC] ${title}`,
      issuetype: { name: "Task" },
      priority:    { name: PRIORITY_MAP[recommendation.priority] || "Medium" },
      description: buildJiraDescription(recommendation, finding),
      labels,
    },
  };

  const response = await axios.post(
    `${baseUrl}/rest/api/2/issue`,
    payload,
    {
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
        Accept:         "application/json",
      },
      timeout: 15000,
    }
  );

  const issueKey = response.data.key;
  const issueUrl = `${baseUrl}/browse/${issueKey}`;
  return { issueKey, issueUrl };
}

module.exports = { createJiraIssue };
